# TODO improve artifacts sharing between the jobs, keep track of the following issues:
# - https://github.com/travis-ci/travis-ci/issues/7590
# - https://travis-ci.community/t/introducing-workspaces/4249
# - https://travis-ci.community/t/allow-to-restore-a-workspace-in-another-os/9165
# - https://travis-ci.community/t/workspaces-do-not-work-nicely-with-cross-platform-builds/4461
# - https://travis-ci.community/t/using-unified-cache-control-cache-identity/1531
# - https://github.com/travis-ci/travis-build/pull/1923

branches:
  only:
    - wip

language: node_js
node_js: 12.16.3

cache:
  yarn: false
  npm: false

embedding-linux-common: &embedding-linux-common-anchor
  os: linux
  dist: bionic
  env:
    # needed for: native modules compiling
    - CC=gcc-7 CXX=g++-7
  addons:
    apt:
      packages:
        # needed for: native modules compiling
        - g++-7
        # needed for: compiling "desktop-idle" native module
        - libxss-dev
        # needed for: keychain initialization and compiling "node-keytar" native module
        - gnome-keyring
        - libgnome-keyring-dev
        - libsecret-1-dev
        # needed for: keychain access testing before running e2e tests (see "scripts/ci/add-secret-service-item-assert.py")
        - python3-secretstorage
        # needed for: tweaking snap package ("unsquashfs" binary)
        - squashfs-tools

embedding-windows-common: &embedding-windows-common-anchor
  os: windows
  before_install:
    - |
      (
        set -Eeuo pipefail
        set -x

        powershell Get-Process

        choco install nodejs --version=12.16.3 --yes
        choco install yarn --yes
        powershell call RefreshEnv.cmd
        echo $(where.exe node.exe)
        echo $(yarn cache dir)

        # enable running local powershell scripts
        powershell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'

        # tackle the performance issue of "yarn install" execution, see https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/15
        export NODEPATH=$(where.exe node.exe)
        export PROJECTDIR=$(pwd)
        export YARNCACHE=$(yarn cache dir)
        export TEMPDIR=$LOCALAPPDATA\\Temp
        powershell Add-MpPreference -ExclusionProcess ${NODEPATH}
        powershell Add-MpPreference -ExclusionPath ${YARNCACHE}
        powershell Add-MpPreference -ExclusionPath ${PROJECTDIR}
        powershell Add-MpPreference -ExclusionPath ${TEMPDIR}
        powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableArchiveScanning \$true'"
        powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableBehaviorMonitoring \$true'"
        powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableRealtimeMonitoring \$true'"
      )

embedding-prepare-webclients-windows-common: &embedding-prepare-webclients-windows-common-anchor
  <<: *embedding-windows-common-anchor
  language: bash
  install:
    - |
      (
        set -Eeuo pipefail
        set -x

        node --version
        npm --version
        yarn --version
        npx envinfo
        yarn install --pure-lockfile --network-timeout 1000000
      )
  script: ./scripts/ci/nix/prepare-webclients.sh

embedding-prepare-webclients-mail-settings: &embedding-prepare-webclients-mail-settings-anchor
  cache:
    directories:
      - output/git/proton-mail-settings
  env:
    - ELECTRON_MAIL_PREPARE_WEBCLIENTS_REPOS_ONLY="proton-mail-settings"
  script: ./scripts/ci/nix/prepare-webclients.sh

embedding-prepare-webclients-contacts: &embedding-prepare-webclients-contacts-anchor
  cache:
    directories:
      - output/git/proton-contacts
  env:
    - ELECTRON_MAIL_PREPARE_WEBCLIENTS_REPOS_ONLY="proton-contacts"
  script: ./scripts/ci/nix/prepare-webclients.sh

embedding-prepare-webclients-calendar: &embedding-prepare-webclients-calendar-anchor
  cache:
    directories:
      - output/git/proton-calendar
  env:
    - ELECTRON_MAIL_PREPARE_WEBCLIENTS_REPOS_ONLY="proton-calendar"
  script: ./scripts/ci/nix/prepare-webclients.sh

embedding-prepare-webclients-webclient: &embedding-prepare-webclients-webclient-anchor
  cache:
    directories:
      - output/git/WebClient
  env:
    - ELECTRON_MAIL_PREPARE_WEBCLIENTS_REPOS_ONLY="WebClient"
  script: ./scripts/ci/nix/prepare-webclients.sh

# TODO drop this anchor on https://github.com/travis-ci/travis-build/pull/1923 resolving
embedding-build-app-common-osx: &embedding-build-app-common-osx-anchor
  os: osx
  workspaces:
    use:
      - 'webclients-artifact-mail-settings-osx'
      - 'webclients-artifact-contacts-osx'
      - 'webclients-artifact-calendar-osx'
      - 'webclients-artifact-webclient-osx'

install:
  - node --version
  - npm --version
  - yarn --version
  - npx envinfo
  - yarn install --pure-lockfile --network-timeout 1000000
notifications:
  email:
    on_success: never
    on_failure: change

jobs:
  include:
    # proton clients prepared by jobs used to workaround the issue of travis dropping long-running jobs on a free plan
    # mail-settings
    - stage: 'build proton clients'
      <<: *embedding-linux-common-anchor
      <<: *embedding-prepare-webclients-mail-settings-anchor
      workspaces:
        create:
          name: 'webclients-artifact-mail-settings-linux'
          paths:
            - output/git/proton-mail-settings
    # TODO drop this stage on https://github.com/travis-ci/travis-build/pull/1923 resolving
    - stage: 'build proton clients'
      os: osx
      <<: *embedding-prepare-webclients-mail-settings-anchor
      workspaces:
        create:
          name: 'webclients-artifact-mail-settings-osx'
          paths:
            - output/git/proton-mail-settings
    # TODO drop this stage on https://github.com/travis-ci/travis-build/pull/1923 resolving
    - stage: 'build proton clients'
      <<: *embedding-prepare-webclients-mail-settings-anchor
      <<: *embedding-prepare-webclients-windows-common-anchor
      workspaces:
        create:
          name: 'webclients-artifact-mail-settings-windows'
          paths:
            - output/git/proton-mail-settings
      script: docker run -it ubuntu ./scripts/ci/nix/prepare-webclients.sh
    # contacts
    - stage: 'build proton clients'
      <<: *embedding-linux-common-anchor
      <<: *embedding-prepare-webclients-contacts-anchor
      workspaces:
        create:
          name: 'webclients-artifact-contacts-linux'
          paths:
            - output/git/proton-contacts
    # TODO drop this stage on https://github.com/travis-ci/travis-build/pull/1923 resolving
    - stage: 'build proton clients'
      os: osx
      <<: *embedding-prepare-webclients-contacts-anchor
      workspaces:
        create:
          name: 'webclients-artifact-contacts-osx'
          paths:
            - output/git/proton-contacts
    # TODO drop this stage on https://github.com/travis-ci/travis-build/pull/1923 resolving
    - stage: 'build proton clients'
      <<: *embedding-prepare-webclients-contacts-anchor
      <<: *embedding-prepare-webclients-windows-common-anchor
      workspaces:
        create:
          name: 'webclients-artifact-contacts-windows'
          paths:
            - output/git/proton-contacts
    # calendar
    - stage: 'build proton clients'
      <<: *embedding-linux-common-anchor
      <<: *embedding-prepare-webclients-calendar-anchor
      workspaces:
        create:
          name: 'webclients-artifact-calendar-linux'
          paths:
            - output/git/proton-calendar
    # TODO drop this stage on https://github.com/travis-ci/travis-build/pull/1923 resolving
    - stage: 'build proton clients'
      os: osx
      <<: *embedding-prepare-webclients-calendar-anchor
      workspaces:
        create:
          name: 'webclients-artifact-calendar-osx'
          paths:
            - output/git/proton-calendar
    # TODO drop this stage on https://github.com/travis-ci/travis-build/pull/1923 resolving
    - stage: 'build proton clients'
      <<: *embedding-prepare-webclients-calendar-anchor
      <<: *embedding-prepare-webclients-windows-common-anchor
      workspaces:
        create:
          name: 'webclients-artifact-calendar-windows'
          paths:
            - output/git/proton-calendar
    # WebClient
    - stage: 'build proton clients'
      <<: *embedding-linux-common-anchor
      <<: *embedding-prepare-webclients-webclient-anchor
      workspaces:
        create:
          name: 'webclients-artifact-webclient-linux'
          paths:
            - output/git/WebClient
    # TODO drop this stage on https://github.com/travis-ci/travis-build/pull/1923 resolving
    - stage: 'build proton clients'
      os: osx
      <<: *embedding-prepare-webclients-webclient-anchor
      workspaces:
        create:
          name: 'webclients-artifact-webclient-osx'
          paths:
            - output/git/WebClient
    # TODO drop this stage on https://github.com/travis-ci/travis-build/pull/1923 resolving
    - stage: 'build proton clients'
      <<: *embedding-prepare-webclients-webclient-anchor
      <<: *embedding-prepare-webclients-windows-common-anchor
      workspaces:
        create:
          name: 'webclients-artifact-webclient-windows'
          paths:
            - output/git/WebClient
    # app building stages
    - stage: 'build app'
      <<: *embedding-windows-common-anchor
      workspaces:
        use:
          - 'webclients-artifact-mail-settings-windows'
          - 'webclients-artifact-contacts-windows'
          - 'webclients-artifact-calendar-windows'
          - 'webclients-artifact-webclient-windows'
      script: ./scripts/ci/travis/build-windows.sh
    - stage: 'build app'
      osx_image: xcode9.4
      <<: *embedding-build-app-common-osx-anchor
      env:
        - ARTIFACT_NAME_POSTFIX="-high-sierra"
      script: ./scripts/ci/travis/build-osx.sh
    - stage: 'build app'
      osx_image: xcode11.3 # same xcode version as used at "appveyor" for "mojave" system version
      <<: *embedding-build-app-common-osx-anchor
      env:
        - ARTIFACT_NAME_POSTFIX="-mojave"
      script: ./scripts/ci/travis/build-osx.sh
    - stage: 'build app'
      osx_image: xcode11.5 # same xcode version as used at "appveyor" for "catalina" system version
      <<: *embedding-build-app-common-osx-anchor
      env:
        - ARTIFACT_NAME_POSTFIX="-catalina"
      script: ./scripts/ci/travis/build-osx.sh
    - stage: 'build app'
      <<: *embedding-linux-common-anchor
      workspaces:
        use:
          - 'webclients-artifact-mail-settings-linux'
          - 'webclients-artifact-contacts-linux'
          - 'webclients-artifact-calendar-linux'
          - 'webclients-artifact-webclient-linux'
      sudo: required
      services:
        - docker
        - xvfb # needed for: running e2e tests
      before_script:
        - | # init dbus
          NO_AT_BRIDGE=1;
          eval $(dbus-launch --sh-syntax);
        # TODO get back keyring initialization then enable respective e2e test case (see "src/e2e/index.spec.ts")
        #- | # init keychain
        #  eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login);
        #  eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start);
        #  python3 ./scripts/ci/add-secret-service-item-assert.py;
      script: ./scripts/ci/travis/build-linux.sh
